apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: benjaminstrandberg123/pss-backend:latest
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "testdb"
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 5000
